# Generated by Django 5.1.3 on 2024-11-18 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id_lieu', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('type_lieu', models.CharField(choices=[('forteresse', 'Forteresse'), ('forêt', 'Forêt'), ('village', 'Village'), ('donjon', 'Donjon')], max_length=50)),
                ('disponibilite', models.CharField(choices=[('libre', 'Libre'), ('occupé', 'Occupé')], max_length=20)),
                ('niveau_acces', models.IntegerField(default=1)),
                ('capacite_max', models.IntegerField(default=10)),
                ('photo', models.ImageField(upload_to='lieux/')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id_character', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('etat', models.CharField(max_length=20)),
                ('niveau', models.IntegerField(default=1)),
                ('type', models.CharField(choices=[('Guerrier', 'Guerrier'), ('Mage', 'Mage'), ('Archer', 'Archer')], max_length=20)),
                ('team', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='characters/')),
                ('lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeu_de_role.lieu')),
            ],
        ),
    ]
